[package]
name = "ws2812-flexio"
version = "0.1.0"
edition = "2021"
authors = ["Finomnis <finomnis@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Finomnis/ws2812-flexio"
description = "A neopixel driver based on NXP i.MX RT's FlexIO bus."
keywords = ["ws2812", "neopixel", "flexio", "imxrt", "nxp"]
categories = ["embedded", "no-std"]

exclude = ["/.gitignore", "/.github/", "/.vscode/"]

[dependencies]
imxrt-hal = "0.5.3"
imxrt-ral = "0.5.1"
log = "0.4.19"
paste = "1.0.12"
snafu = { version = "0.7.4", default-features = false }

# Pixel types
palette = { version = "0.7.2", default-features = false, features = ["libm"] }

# Async reactor, for executing DMA actions
cassette = "0.2.3"


[dev-dependencies]
cortex-m = "0.7.7"
embedded-hal = "0.2.7"

# Board support package
teensy4-bsp = { version = "0.4.3", features = ["rt"] }

# Logging
critical-section = "1.1.1"

# Packages necessary for board usage
nb = "1.1.0"    # Async
fugit = "0.3.6" # Time

# Allow docsrs options
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
