[package]
name = "ws2812-flexio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
smart-leds-trait = ["dep:smart-leds-trait"]
palette = ["dep:palette"]

[dependencies]
imxrt-hal = "0.5.2"
imxrt-ral = "0.5.0"
log = "0.4.19"
paste = "1.0.12"
snafu = { version = "0.7.4", default-features = false }

# Pixel types
smart-leds-trait = { version = "0.2.1", optional = true, default-features = false }
palette = { version = "0.7.2", optional = true, default-features = false, features = [
    "libm",
] }


[dev-dependencies]

# Base dependencies
cortex-m = "0.7.7"
embedded-hal = "0.2.7"

# Board support package
teensy4-bsp = { version = "0.4.2", features = ["rt"] }

# Logging
critical-section = "1.1.1"

# Packages necessary for board usage
nb = "1.1.0"    # Async
fugit = "0.3.6" # Time


# For local development of imxrt-hal
[patch.crates-io]
imxrt-ral = { git = "https://github.com/Finomnis/imxrt-ral.git", branch = "pinsel_5bit" }
imxrt-hal = { git = "https://github.com/Finomnis/imxrt-hal.git", branch = "flexio" }
imxrt-iomuxc = { git = "https://github.com/Finomnis/imxrt-iomuxc.git", branch = "flexio_0.2.1" }
teensy4-bsp = { git = "https://github.com/Finomnis/teensy4-rs.git", branch = "flexio" }

# Allow docsrs options
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
